### ISSUE TITLE
SVG2 (SVG 1.3) not compatible : "An error was verified during your last svg processed"

### ISSUE THREAD

**Issue by aldaw** [elrumordelaluz/svgsprit.es#16]
First i want to thank you, for all your efforts and all your time you have put into this project! :)

I have tried now several .svg, i had even problem with illustrator and wrote a issue there.
The version of my .svg is simply to new nothing seems to be compatible right now, only afinity desginer on ipad, a app for 20 bucks was able to.
So if Illustrator is to dump and a 20 bucks app is capable to keep the compatible formats uptodate, you should be even faster xD

Here a are the SVGs which i tried to use https://github.com/spothq/cryptocurrency-icons/tree/master/svg
I can find it anymore but i thing it is kinda svg version 1.3 even? at least 1.2.

Here if you want to waste your time that illustrator is simple not up to date, also also bugging arround with newest svg.
https://community.adobe.com/t5/illustrator/svg-files-doesn-t-open-correctly-illustrator/m-p/11392589?page=1#M190720

EDIT: I kinda found it now, they called it for sure 1.3 back, I am 100% sure at least at the svg img github repo i posted above.
But seems now it is now baptised to just SVG 2 instead of 1.3 just to make things clearly.
https://en.wikipedia.org/wiki/Scalable_Vector_Graphics
Under Development history, 1.2 was dorpped for SVG 2 (maybe internel at the beginning 1.3)
Latest Draft to SVG 2 from may 2020
https://www.w3.org/TR/SVG2/

**Comment by elrumordelaluz** [comment]
Hi @aldaw, thanks for open the _Issue_.

Could you please try again, since I just deployed an update with a fix on the core _package_.

From my end I can create a _Sprite_ from the entire _Icon package_ you are pointing to.

[Here](https://codepen.io/elrumordelaluz/pen/pobJqNv) is an example I create right now.

<img width="1552" alt="Screenshot 2020-10-12 at 12 24 42" src="https://user-images.githubusercontent.com/784056/95736003-ee1d1880-0c85-11eb-950d-391f644edde0.png">

**Comment by aldaw** [comment]
@elrumordelaluz You are a genius! :D It seems to work like a charm now <3
I should have wrote that earlier xD 

Thank you so much for all your time and efforts! People like you define the internet! <3
